package com.everis.examen2academia.model;
// Generated 20/09/2019 01:26:58 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria", catalog = "examen2")
public class Categoria implements java.io.Serializable {

	private int idCategoria;
	private String categoria;
	@JsonIgnore
	private Set<Producto> productos = new HashSet<Producto>(0);

	public Categoria() {
	}

	public Categoria(int idCategoria, String categoria) {
		this.idCategoria = idCategoria;
		this.categoria = categoria;
	}

	public Categoria(int idCategoria, String categoria, Set<Producto> productos) {
		this.idCategoria = idCategoria;
		this.categoria = categoria;
		this.productos = productos;
	}

	@Id

	@Column(name = "idCategoria", unique = true, nullable = false)
	public int getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(int idCategoria) {
		this.idCategoria = idCategoria;
	}

	@Column(name = "categoria", nullable = false, length = 45)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

}
